### ISSUE TITLE
HP Checklist/Notes

### ISSUE THREAD

**Issue by ejw7** [carissacase/Harry-Potter-Project#1]
look for:

- Differences
- Characters - For script: \s{37}([A-Z]+((\s|\-)?[A-Z]+))
- attributes , professors, house
- Spells (in book are all in italics)
- location?
- Creatures
- Items 

Checklist:

- [x] Mark up characters
- [ ] Mark up characters mentioned in script
- [ ] Create and work on Schema
- [x] Mark up locations in script

Checklist for Book:

- [ ] Chapters
- [ ] Characters
- [ ] Locations
- [ ] Create a Schema
